name: BedWars1058-WinStreak
version: ${version}
main: com.reussy.exodus.winstreak.plugin.WinStreakPlugin
softdepend: [ BedWars1058, BedWarsProxy, PlaceholderAPI ]
authors: [ reussy ]
api-version: 1.13
description: Win Streak system for BedWars players!
